languageCode: "jp"
metaDataFormat: "yaml"
title: "MLSBLG"
baseURL: "/"
rssuri: "feed.xml"
copyright: "2012 rnelo_so, all rights reserved."
theme: "hugo-zen-mod"
canonifyurls: true
googleAnalytics: "UA-39084608-1"
permalinks:
    post: /:year/:month/:slug/

taxonomies:
    tag: "tags"

params:
